module

-- BEGIN GENERATED VOCABULARY: generated by scripts/challenge-prep.py from the Vocabulary modules; edit those, then run `python3 scripts/challenge-prep.py sync`.
public import Mathlib

@[expose] public section

-- from Vocabulary.lean
/-!
# Challenge vocabulary: the ambient space, space-time derivatives, strict ordering on a set

Part of the trusted statement surface; imports `Mathlib` only. Restates, token for token, the
definitions of the library file `BernoulliComparison/Interface/Setting.lean`.

* `E d` is `EuclideanSpace ℝ (Fin d)`. Space-time points are `p : E d × ℝ`, with `p.1` the space
  and `p.2` the time variable. The product `E d × ℝ` carries Mathlib's product (sup) metric; no
  statement below uses space-time balls.
* `gradₓ`, `lapₓ`, `dₜ` are Mathlib's `gradient` (`∇`), `InnerProductSpace.laplacian` (`Δ`) and
  `deriv`, applied to the time slice `y ↦ φ (y, t)` (for `∇`, `Δ`) or to the space slice
  `s ↦ φ (x, s)` (for `∂ₜ`) through `p = (x, t)`. They are only ever applied to `C^∞` functions.
* `PrecOn u v E F` is the strict ordering `u < v` on `E ∩ F`.
-/

open Set Filter Topology
open scoped Gradient Laplacian

namespace BernoulliComparison

/-- The ambient Euclidean space `ℝᵈ`. -/
abbrev E (d : ℕ) := EuclideanSpace ℝ (Fin d)

variable {d : ℕ}

/-- Spatial gradient `∇ₓφ(x, t)`: the gradient of the time slice `y ↦ φ (y, t)` at `x`. -/
noncomputable def gradₓ (φ : E d × ℝ → ℝ) (p : E d × ℝ) : E d :=
  ∇ (fun y ↦ φ (y, p.2)) p.1

/-- Spatial Laplacian `Δₓφ(x, t)`: the Laplacian of the time slice `y ↦ φ (y, t)` at `x`. -/
noncomputable def lapₓ (φ : E d × ℝ → ℝ) (p : E d × ℝ) : ℝ :=
  Δ (fun y ↦ φ (y, p.2)) p.1

/-- Time derivative `∂ₜφ(x, t)`: the derivative of `s ↦ φ (x, s)` at `t`. -/
noncomputable def dₜ (φ : E d × ℝ → ℝ) (p : E d × ℝ) : ℝ :=
  deriv (fun s ↦ φ (p.1, s)) p.2

section PrecOn

variable {X : Type*}

/-- `u ≺_E v` on `F`: `u < v` at every point of `E ∩ F`. -/
def PrecOn (u v : X → ℝ) (Eset F : Set X) : Prop := ∀ p ∈ Eset ∩ F, u p < v p

end PrecOn

end BernoulliComparison

/-!
# Challenge vocabulary: barrier (comparison) solutions of the parabolic Bernoulli problem

Part of the trusted statement surface; imports `Mathlib` only (earlier in this file).
Restates, token for token, the definitions of the library file
`BernoulliComparison/Interface/Parabolic.lean` that the challenge statements use.

The free boundary problem is

  `∂ₜu = Δu` in `{u > 0}`,  `|∇u| = Q` on `∂{u > 0}`,  `u ≥ 0`,

in a space-time domain `U × I`. Solutions are defined by comparison with classical strict
barriers on test cylinders:

* a test cylinder is `V × (a, b]` with `V` open and bounded, `a < b`, and `V̄ × [a, b] ⊆ U × I`
  (`AdmissibleCyl`);
* a classical strict subsolution (`IsClassicalStrictParaSub`) is a `C^∞` function `φ` on all of
  space-time with `∂ₜφ - Δφ < 0` on `closure {φ > 0}` and `|∇φ| > Q` on `∂{φ > 0}`, both
  within `V̄ × [a, b]`; a classical strict supersolution reverses both strict inequalities;
* `u` is a supersolution (`IsParaSuper`) if it is continuous and nonnegative on `U × I` and no
  classical strict subsolution can cross it from below: whenever `φ ≺ u` on the parabolic
  boundary `∂_P(V × (a, b]) = (V̄ × {a}) ∪ (∂V × [a, b])` of a test cylinder, also `φ ≺ u` in
  `V × (a, b]`. Here `φ ≺ u` means `φ < u` on `closure {φ > 0}` (`Prec`), so the barrier is
  compared with `u` on its own positivity set and not where it is negative;
* `u` is a subsolution (`IsParaSub`) symmetrically: `u ≺ φ` (that is, `u < φ` on
  `closure {u > 0}`) propagates from `∂_P(V × (a, b])` into `V × (a, b]` for every classical
  strict supersolution `φ`;
* a relaxed subsolution `(u, E)` (`IsParaRelaxedSub`) is the same with the positivity set of `u`
  replaced by a given closed set `E ⊆ Ū × Ī` containing `{u > 0}`: the ordering is `u < φ` on
  `E` (`PrecOn u φ E`). For `E = closure {u > 0}` this is exactly `IsParaSub`.

The positivity set `{φ > 0}` of a barrier, its closure and its boundary are taken in all of
space-time; the positivity set of `u` is taken inside the domain `U × I` (`posSetP`).
-/

open Set Filter Topology
open scoped ContDiff

namespace BernoulliComparison

variable {d : ℕ}

/-- The cylinder `V × (a, b]`. -/
def cyl (V : Set (E d)) (a b : ℝ) : Set (E d × ℝ) := V ×ˢ Ioc a b

/-- The parabolic boundary `∂_P(V × (a, b]) = (V̄ × {a}) ∪ (∂V × [a, b])`. -/
def parBdry (V : Set (E d)) (a b : ℝ) : Set (E d × ℝ) :=
  (closure V ×ˢ {a}) ∪ (frontier V ×ˢ Icc a b)

/-- `V × (a, b]` is a test cylinder compactly contained in `U × I`: `V` is open and bounded,
`a < b`, and `V̄ × [a, b] ⊆ U × I`. -/
def AdmissibleCyl (U : Set (E d)) (I : Set ℝ) (V : Set (E d)) (a b : ℝ) : Prop :=
  IsOpen V ∧ Bornology.IsBounded V ∧ a < b ∧ closure V ×ˢ Icc a b ⊆ U ×ˢ I

/-- The positivity set `{u > 0}` of `u` inside the domain `Ω`. -/
def posSetP (u : E d × ℝ → ℝ) (Ω : Set (E d × ℝ)) : Set (E d × ℝ) := {p ∈ Ω | 0 < u p}

/-- `u ≺ v` on `F`: `u < v` on `closure {u > 0} ∩ F`, with `{u > 0}` taken inside `Ω`. -/
def Prec (u v : E d × ℝ → ℝ) (Ω F : Set (E d × ℝ)) : Prop :=
  PrecOn u v (closure (posSetP u Ω)) F

/-- `φ` is a classical strict subsolution on `V̄ × [a, b]`: `φ` is `C^∞` on space-time,
`∂ₜφ - Δφ < 0` on `closure {φ > 0} ∩ (V̄ × [a, b])`, and `|∇φ| > Q` on
`∂{φ > 0} ∩ (V̄ × [a, b])`. -/
def IsClassicalStrictParaSub (Q : E d → ℝ) (φ : E d × ℝ → ℝ) (V : Set (E d)) (a b : ℝ) :
    Prop :=
  ContDiff ℝ ∞ φ ∧
    (∀ p ∈ closure {q | 0 < φ q} ∩ (closure V ×ˢ Icc a b), dₜ φ p - lapₓ φ p < 0) ∧
    ∀ p ∈ frontier {q | 0 < φ q} ∩ (closure V ×ˢ Icc a b), Q p.1 < ‖gradₓ φ p‖

/-- `φ` is a classical strict supersolution on `V̄ × [a, b]`: `φ` is `C^∞` on space-time,
`∂ₜφ - Δφ > 0` on `closure {φ > 0} ∩ (V̄ × [a, b])`, and `|∇φ| < Q` on
`∂{φ > 0} ∩ (V̄ × [a, b])`. -/
def IsClassicalStrictParaSuper (Q : E d → ℝ) (φ : E d × ℝ → ℝ) (V : Set (E d)) (a b : ℝ) :
    Prop :=
  ContDiff ℝ ∞ φ ∧
    (∀ p ∈ closure {q | 0 < φ q} ∩ (closure V ×ˢ Icc a b), 0 < dₜ φ p - lapₓ φ p) ∧
    ∀ p ∈ frontier {q | 0 < φ q} ∩ (closure V ×ˢ Icc a b), ‖gradₓ φ p‖ < Q p.1

/-- **Supersolution** in `U × I`. `u` is continuous and nonnegative on `U × I`, and for every
test cylinder `V × (a, b]` and every classical strict subsolution `φ` on `V̄ × [a, b]`, if
`φ < u` on `closure {φ > 0} ∩ ∂_P(V × (a, b])`, then `φ < u` on
`closure {φ > 0} ∩ (V × (a, b])`. -/
def IsParaSuper (U : Set (E d)) (Q : E d → ℝ) (I : Set ℝ) (u : E d × ℝ → ℝ) : Prop :=
  ContinuousOn u (U ×ˢ I) ∧ (∀ p ∈ U ×ˢ I, 0 ≤ u p) ∧
    ∀ (V : Set (E d)) (a b : ℝ) (φ : E d × ℝ → ℝ), AdmissibleCyl U I V a b →
      IsClassicalStrictParaSub Q φ V a b → Prec φ u univ (parBdry V a b) →
        Prec φ u univ (cyl V a b)

/-- **Subsolution** in `U × I`. `u` is continuous and nonnegative on `U × I`, and for every
test cylinder `V × (a, b]` and every classical strict supersolution `φ` on `V̄ × [a, b]`, if
`u < φ` on `closure {u > 0} ∩ ∂_P(V × (a, b])`, then `u < φ` on
`closure {u > 0} ∩ (V × (a, b])`; here `{u > 0}` is taken inside `U × I`. -/
def IsParaSub (U : Set (E d)) (Q : E d → ℝ) (I : Set ℝ) (u : E d × ℝ → ℝ) : Prop :=
  ContinuousOn u (U ×ˢ I) ∧ (∀ p ∈ U ×ˢ I, 0 ≤ u p) ∧
    ∀ (V : Set (E d)) (a b : ℝ) (φ : E d × ℝ → ℝ), AdmissibleCyl U I V a b →
      IsClassicalStrictParaSuper Q φ V a b → Prec u φ (U ×ˢ I) (parBdry V a b) →
        Prec u φ (U ×ˢ I) (cyl V a b)

/-- **Relaxed subsolution** `(u, E)` in `U × I`. `u` is continuous and nonnegative on `U × I`;
`E` is a closed subset of `Ū × Ī` containing `{u > 0}` (taken inside `U × I`); and for every
test cylinder `V × (a, b]` and every classical strict supersolution `φ` on `V̄ × [a, b]`, if
`u < φ` on `E ∩ ∂_P(V × (a, b])`, then `u < φ` on `E ∩ (V × (a, b])`. -/
def IsParaRelaxedSub (U : Set (E d)) (Q : E d → ℝ) (I : Set ℝ) (u : E d × ℝ → ℝ)
    (Eset : Set (E d × ℝ)) : Prop :=
  ContinuousOn u (U ×ˢ I) ∧ (∀ p ∈ U ×ˢ I, 0 ≤ u p) ∧ IsClosed Eset ∧
    Eset ⊆ closure U ×ˢ closure I ∧ posSetP u (U ×ˢ I) ⊆ Eset ∧
    ∀ (V : Set (E d)) (a b : ℝ) (φ : E d × ℝ → ℝ), AdmissibleCyl U I V a b →
      IsClassicalStrictParaSuper Q φ V a b → PrecOn u φ Eset (parBdry V a b) →
        PrecOn u φ Eset (cyl V a b)

end BernoulliComparison
-- END GENERATED VOCABULARY

/-!
# Challenge: comparison for the parabolic Bernoulli problem

Trusted statement surface for the comparison principle for

  `∂ₜu = Δu` in `{u > 0}`,  `|∇u| = Q` on `∂{u > 0}`

in `U × (0, T]`, between a supersolution and a (relaxed) subsolution in the barrier sense. The
project vocabulary is restated above, token for token, from the library files
`Interface/Setting.lean` (the space `E d`, the operators `gradₓ`, `lapₓ`, `dₜ`, and the ordering
`PrecOn`) and `Interface/Parabolic.lean` (cylinders, parabolic boundaries, classical strict
barriers, and the solution notions `IsParaSuper`, `IsParaSub`, `IsParaRelaxedSub`); it imports
`Mathlib` only. The second module docstring of the vocabulary explains the definitions.

The third statement, `challenge_model_sanity`, is a non-vacuity and sign-convention check of these
solution classes, not a headline result.

Common hypotheses of both statements:

* `U ⊆ ℝᵈ` is open and bounded; `T > 0`;
* `Q` is Lipschitz on `Ū` and bounded below on `Ū` by a positive constant;
* `u` and `v` are continuous on `Ū × [0, T]` (the solution notions only require continuity on
  `U × (0, T]`);
* the ordering holds on some neighbourhood `N` of the parabolic boundary
  `∂_P(U × (0, T]) = (Ū × {0}) ∪ (∂U × [0, T])` (a set `N` with `N ∈ 𝓝ˢ (parBdry U 0 T)`).

The conclusion is the strict ordering on `Ū × [0, T]`. It is strict only on the ordering set:
`u < v` on `E ∩ (Ū × [0, T])` in the relaxed form and on `closure {u > 0} ∩ (Ū × [0, T])` in the
standard form. Off that set `u ≤ 0 ≤ v` holds in `U × (0, T]` by the definitions.
-/

open Set Filter Topology Metric

namespace BernoulliComparison

variable {d : ℕ}

/-- **Comparison principle, relaxed form.** Let `U ⊆ ℝᵈ` be open and bounded, `Q` Lipschitz on
`Ū` with a positive lower bound on `Ū`, `T > 0`, and `u, v` continuous on `Ū × [0, T]`. Let
`(u, E)` be a relaxed subsolution and `v` a supersolution in `U × (0, T]`. If `u < v` on
`E ∩ N` for a neighbourhood `N` of the parabolic boundary `∂_P(U × (0, T])`, then `u < v` on
`E ∩ (Ū × [0, T])`.

`E` is part of the data of the relaxed subsolution: `hsub` requires `E` to be closed, contained
in `Ū × [0, T]` (`closure (Ioc 0 T) = Icc 0 T` as `T > 0`), and to contain `{u > 0}`. -/
theorem challenge_relaxed_comparison {U : Set (E d)} {Q : E d → ℝ} {T : ℝ}
    {u v : E d × ℝ → ℝ} {Eset N : Set (E d × ℝ)} (hU : IsOpen U) (hUb : Bornology.IsBounded U)
    (hQ : ∃ K, LipschitzOnWith K Q (closure U)) (hQpos : ∃ c > 0, ∀ x ∈ closure U, c ≤ Q x)
    (hT : 0 < T) (hu : ContinuousOn u (closure U ×ˢ Icc 0 T))
    (hv : ContinuousOn v (closure U ×ˢ Icc 0 T))
    (hsub : IsParaRelaxedSub U Q (Ioc 0 T) u Eset) (hsuper : IsParaSuper U Q (Ioc 0 T) v)
    (hN : N ∈ 𝓝ˢ (parBdry U 0 T)) (hprec : PrecOn u v Eset N) :
    PrecOn u v Eset (closure U ×ˢ Icc 0 T) := by
  sorry

/-- **Comparison principle, standard form.** Same setting, with `u` a subsolution. Write
`P = closure {u > 0}`, with `{u > 0}` taken in `Ū × [0, T]`. If `u < v` on `P ∩ N` for a
neighbourhood `N` of the parabolic boundary `∂_P(U × (0, T])`, then `u < v` on
`P ∩ (Ū × [0, T])`.

This is a corollary of `challenge_relaxed_comparison` with `E = P` (a subsolution `u` makes
`(u, P)` a relaxed subsolution), so it adds little independent coverage. -/
theorem challenge_strict_comparison {U : Set (E d)} {Q : E d → ℝ} {T : ℝ}
    {u v : E d × ℝ → ℝ} (hU : IsOpen U) (hUb : Bornology.IsBounded U)
    (hQ : ∃ K, LipschitzOnWith K Q (closure U)) (hQpos : ∃ c > 0, ∀ x ∈ closure U, c ≤ Q x)
    (hT : 0 < T) (hu : ContinuousOn u (closure U ×ˢ Icc 0 T))
    (hv : ContinuousOn v (closure U ×ˢ Icc 0 T))
    (hsub : IsParaSub U Q (Ioc 0 T) u) (hsuper : IsParaSuper U Q (Ioc 0 T) v)
    {N : Set (E d × ℝ)} (hN : N ∈ 𝓝ˢ (parBdry U 0 T))
    (hprec : Prec u v (closure U ×ˢ Icc 0 T) N) :
    Prec u v (closure U ×ˢ Icc 0 T) (closure U ×ˢ Icc 0 T) := by
  sorry

/-- **Non-vacuity and sign-convention check** of the solution classes in the two comparison
statements; not a headline result. It guards against solution classes that are empty, trivially
true, or carry the wrong sign. All functions are explicit, on `ℝᵈ × ℝ` for any dimension `d`.

`challenge_model_sanity` is the conjunction of:

1. **An explicit strict supersolution barrier.** `φ(x, t) = 1 + t - |x|²` is a classical strict
   supersolution for `Q ≡ 3` on `B̄₂(0) × [0, 1]`: `∂ₜφ - Δφ = 1 + 2d > 0`, and on the free
   boundary `{|x|² = 1 + t}` one has `|∇φ| = 2|x| ≤ 2√2 < 3`. So the barrier class used in the
   definition of subsolutions is non-empty.
2. **The free-boundary clause of (1) is not vacuous.** For `d ≥ 1`, the free boundary
   `∂{φ > 0}` meets `B̄₂(0) × [0, 1]`.
3. **An explicit strict subsolution barrier.** `ψ(x, t) = 1 - |x|² - (2d + 1)t` is a classical
   strict subsolution for `Q ≡ 1` on `B̄₂(0) × [0, T_d]`, `T_d = 1/(4d + 2)`. Its positivity set
   is the shrinking ball `{|x|² < 1 - (2d + 1)t}`, and `∂ₜψ - Δψ = -1 < 0`. On the free boundary
   `|∇ψ| = 2|x| = 2√(1 - (2d + 1)t)`, which tends to `0` as the ball vanishes at `t = 1/(2d + 1)`;
   up to `T_d` one has `|x|² ≥ 1/2`, so `|∇ψ| ≥ √2 > 1`. So the barrier class used in the
   definition of supersolutions is non-empty, and the time restriction is genuinely needed.
4. **The free-boundary clause of (3) is not vacuous.** For `d ≥ 1`, the free boundary
   `∂{ψ > 0}` meets `B̄₂(0) × [0, T_d]`.
5. **Positive constants are supersolutions**, for every domain `U × I` and every `Q`.
6. **`(0, ∅)` is a relaxed subsolution**, for every domain `U × I` and every `Q`.
7. **Sign convention (negative test).** `v(x, t) = 1 - t/2` is **not** a supersolution in
   `B₂(0) × (0, 1]`, for any `Q`. It is positive there and `∂ₜv - Δv = -1/2 < 0`, so it is a
   strict subsolution of the heat equation. A definition with the time direction or the sign of
   the heat operator reversed would accept it. -/
theorem challenge_model_sanity (d : ℕ) :
    IsClassicalStrictParaSuper (fun _ ↦ 3) (fun p : E d × ℝ ↦ 1 + p.2 - ‖p.1‖ ^ 2)
        (ball 0 2) 0 1 ∧
      (0 < d → (frontier {p : E d × ℝ | 0 < 1 + p.2 - ‖p.1‖ ^ 2} ∩
        (closure (ball (0 : E d) 2) ×ˢ Icc 0 1)).Nonempty) ∧
      IsClassicalStrictParaSub (fun _ ↦ 1)
        (fun p : E d × ℝ ↦ 1 - ‖p.1‖ ^ 2 - (2 * d + 1) * p.2) (ball 0 2) 0 (1 / (4 * d + 2)) ∧
      (0 < d → (frontier {p : E d × ℝ | 0 < 1 - ‖p.1‖ ^ 2 - (2 * d + 1) * p.2} ∩
        (closure (ball (0 : E d) 2) ×ˢ Icc (0 : ℝ) (1 / (4 * d + 2)))).Nonempty) ∧
      (∀ (U : Set (E d)) (Q : E d → ℝ) (I : Set ℝ) (c : ℝ), 0 < c →
        IsParaSuper U Q I (fun _ ↦ c)) ∧
      (∀ (U : Set (E d)) (Q : E d → ℝ) (I : Set ℝ), IsParaRelaxedSub U Q I (fun _ ↦ 0) ∅) ∧
      ∀ Q : E d → ℝ, ¬ IsParaSuper (ball (0 : E d) 2) Q (Ioc 0 1) (fun p ↦ 1 - p.2 / 2) := by
  sorry

end BernoulliComparison
